## Mission 2: Exploring and Analyzing Data with Pandas

Objective:

In this mission, you will perform Exploratory Data Analysis (EDA) and basic data manipulation using Pandas. You will work with a dataset that includes information about employees and apply various data transformation techniques, including handling missing values, filtering, and performing basic data analysis.

Dataset Overview:

The dataset contains the following columns:

employee_id: Unique identifier for each employee.

name: Name of the employee.

age: Age of the employee.

department: The department where the employee works (e.g., HR, Engineering, Marketing).

salary: Annual salary of the employee.

work_experience: Number of years of work experience the employee has.

## Task 1: Load the Data
Objective: Load the dataset into a Pandas DataFrame.

Instructions:

Create a DataFrame from the provided dataset.

Display the first few rows of the dataset to ensure it loaded correctly.

In [1]:
import pandas as pd

# Create a basic dataset
data = {
    'employee_id': range(1, 21),
    'name': ['John', 'Jane', 'Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Hannah', 'Ivy', 'Jack', 'Karen', 'Leo', 'Mia', 'Nina', 'Olivia', 'Paul', 'Quinn', 'Rita'],
    'age': [22, 25, 28, 35, 40, 42, 50, 60, 65, 30, 28, 24, 37, 41, 48, 33, 29, 32, 45, 38],
    'department': ['HR', 'Engineering', 'Marketing', 'Finance', 'Sales', 'HR', 'Engineering', 'Marketing', 'Finance', 'Sales', 'HR', 'Engineering', 'Marketing', 'Finance', 'Sales', 'HR', 'Engineering', 'Marketing', 'Finance', 'Sales'],
    'salary': [50000, 60000, 55000, 75000, 80000, 85000, 100000, 110000, 120000, 65000, 67000, 72000, 85000, 90000, 95000, 48000, 67000, 70000, 80000, 88000],
    'work_experience': [1, 3, 5, 7, 10, 12, 15, 18, 20, 3, 1, 6, 4, 8, 5, 7, 3, 2, 6, 5],
}


# Creating dataframe
df = pd.DataFrame(data)

# Display few rows from dataset
display(df.head())

### Task 2: Data Exploration

Objective: Explore the dataset to get an understanding of its structure.

Instructions:

Check for missing values in the dataset.

Get the summary statistics of numeric columns (age, salary, work_experience).

In [2]:
## Finding missing values in dataset
missing_values = df.isnull()
display(missing_values)

In [3]:
# finding summary statistics (mean. median, std, min, and max) of numeric columns (age, salary, work_experience).
age_mean = df['age'].mean() 
age_median = df['age'].median()
age_std = df['age'].std()
age_min = df['age'].min()
age_max = df['age'].max()

salary_mean = df['salary'].mean()
salary_median = df['salary'].median()
salary_std = df['salary'].std()
salary_min = df['salary'].min()
salary_max = df['salary'].max()

work_experience_mean = df['work_experience'].mean()
work_experience_median = df['work_experience'].median()
work_experience_std = df['work_experience'].std()
work_experience_min = df['work_experience'].min()
work_experience_max = df['work_experience'].max()

display(f"Age - Average: {age_mean}, Median: {age_median}, STD: {age_std}, Minimum: {age_min}, Maximum: {age_max}")
display(f"Salary - Average: {salary_mean}, Median: {salary_median}, STD: {salary_std}, Minimum: {salary_min}, Maximum: {salary_max}")
display(f"Work Experience - Mean: {work_experience_mean}, Median: {work_experience_median}, STD: {work_experience_std}, Minimum: {work_experience_min}, Maximum: {work_experience_max}")

'Age - Average: 37.6, Median: 36.0, STD: 11.627553482998906, Minimum: 22, Maximum: 65'

'Salary - Average: 78100.0, Median: 77500.0, STD: 19150.09962870882, Minimum: 48000, Maximum: 120000'

'Work Experience - Mean: 7.05, Median: 5.5, STD: 5.414162714098722, Minimum: 1, Maximum: 20'

### Task 3: Data Transformation

Objective: Perform basic data transformations such as creating new columns and renaming existing ones.

Instructions:

Create a new column called years_to_retirement by subtracting the age from 65.

Rename the salary column to annual_salary.

Sort the DataFrame based on work_experience in descending order.

In [4]:
##Creating new column named 'years_to_retirement'
df['years_to_retirement'] = 65 - df['age']
display(df)

In [5]:
## rename salary column
df.rename(columns={'salary':'annual_salary'}, inplace=True)
df

,employee_id,name,age,department,annual_salary,work_experience,years_to_retirement
0,1,John,22,HR,50000,1,43
1,2,Jane,25,Engineering,60000,3,40
2,3,Alice,28,Marketing,55000,5,37
3,4,Bob,35,Finance,75000,7,30
4,5,Charlie,40,Sales,80000,10,25
5,6,David,42,HR,85000,12,23
6,7,Eve,50,Engineering,100000,15,15
7,8,Frank,60,Marketing,110000,18,5
8,9,Grace,65,Finance,120000,20,0
9,10,Hannah,30,Sales,65000,3,35
10,11,Ivy,28,HR,67000,1,37
11,12,Jack,24,Engineering,72000,6,41
12,13,Karen,37,Marketing,85000,4,28
13,14,Leo,41,Finance,90000,8,24
14,15,Mia,48,Sales,95000,5,17
15,16,Nina,33,HR,48000,7,32
16,17,Olivia,29,Engineering,67000,3,36
17,18,Paul,32,Marketing,70000,2,33
18,19,Quinn,45,Finance,80000,6,20
19,20,Rita,38,Sales,88000,5,27

In [6]:
## Sorting DataFrame based on work_experience in descending order.
df_sorted = df.sort_values(by='work_experience', ascending=False)
df_sorted

,employee_id,name,age,department,annual_salary,work_experience,years_to_retirement
8,9,Grace,65,Finance,120000,20,0
7,8,Frank,60,Marketing,110000,18,5
6,7,Eve,50,Engineering,100000,15,15
5,6,David,42,HR,85000,12,23
4,5,Charlie,40,Sales,80000,10,25
13,14,Leo,41,Finance,90000,8,24
15,16,Nina,33,HR,48000,7,32
3,4,Bob,35,Finance,75000,7,30
18,19,Quinn,45,Finance,80000,6,20
11,12,Jack,24,Engineering,72000,6,41
19,20,Rita,38,Sales,88000,5,27
2,3,Alice,28,Marketing,55000,5,37
14,15,Mia,48,Sales,95000,5,17
12,13,Karen,37,Marketing,85000,4,28
16,17,Olivia,29,Engineering,67000,3,36
9,10,Hannah,30,Sales,65000,3,35
1,2,Jane,25,Engineering,60000,3,40
17,18,Paul,32,Marketing,70000,2,33
0,1,John,22,HR,50000,1,43
10,11,Ivy,28,HR,67000,1,37

### Task 4: Handling Missing Data

Objective: Handle missing data (if any).

Instructions:

Introduce some missing values in the annual_salary column.

Handle the missing data by either filling it with the mean salary or dropping the rows with missing values.

In [7]:
##Introducing missing values to dataset
df.loc[7, 'annual_salary'] = None
df.loc[2, 'annual_salary'] = None

display(df)

In [12]:
df_dropped_row = df.dropna()   #drop rows with missing value in dataset
df_dropped_row

,employee_id,name,age,department,annual_salary,work_experience,years_to_retirement
0,1,John,22,HR,50000.0,1,43
1,2,Jane,25,Engineering,60000.0,3,40
3,4,Bob,35,Finance,75000.0,7,30
4,5,Charlie,40,Sales,80000.0,10,25
5,6,David,42,HR,85000.0,12,23
6,7,Eve,50,Engineering,100000.0,15,15
8,9,Grace,65,Finance,120000.0,20,0
9,10,Hannah,30,Sales,65000.0,3,35
10,11,Ivy,28,HR,67000.0,1,37
11,12,Jack,24,Engineering,72000.0,6,41
12,13,Karen,37,Marketing,85000.0,4,28
13,14,Leo,41,Finance,90000.0,8,24
14,15,Mia,48,Sales,95000.0,5,17
15,16,Nina,33,HR,48000.0,7,32
16,17,Olivia,29,Engineering,67000.0,3,36
17,18,Paul,32,Marketing,70000.0,2,33
18,19,Quinn,45,Finance,80000.0,6,20
19,20,Rita,38,Sales,88000.0,5,27

In [14]:
display(len(df_dropped_row)) # display count of remaining rows in dataset

18

## Task 5: Data Filtering and Selection
Objective: Select specific data based on conditions.

Instructions:

Filter the data to show only employees who are older than 30.

Select only the columns name, age, and annual_salary.

In [18]:
##  filter employees who are older than 30.
filtered_df = df[df['age'] > 30]
filtered_df

,employee_id,name,age,department,annual_salary,work_experience,years_to_retirement
3,4,Bob,35,Finance,75000.0,7,30
4,5,Charlie,40,Sales,80000.0,10,25
5,6,David,42,HR,85000.0,12,23
6,7,Eve,50,Engineering,100000.0,15,15
7,8,Frank,60,Marketing,NaN,18,5
8,9,Grace,65,Finance,120000.0,20,0
12,13,Karen,37,Marketing,85000.0,4,28
13,14,Leo,41,Finance,90000.0,8,24
14,15,Mia,48,Sales,95000.0,5,17
15,16,Nina,33,HR,48000.0,7,32
17,18,Paul,32,Marketing,70000.0,2,33
18,19,Quinn,45,Finance,80000.0,6,20
19,20,Rita,38,Sales,88000.0,5,27

In [20]:
# select and display columns name, age, and annual_salary.
df_selected_column = df[['name', 'age', 'annual_salary']]
df_selected_column

       name  age  annual_salary
0      John   22        50000.0
1      Jane   25        60000.0
2     Alice   28            NaN
3       Bob   35        75000.0
4   Charlie   40        80000.0
5     David   42        85000.0
6       Eve   50       100000.0
7     Frank   60            NaN
8     Grace   65       120000.0
9    Hannah   30        65000.0
10      Ivy   28        67000.0
11     Jack   24        72000.0
12    Karen   37        85000.0
13      Leo   41        90000.0
14      Mia   48        95000.0
15     Nina   33        48000.0
16   Olivia   29        67000.0
17     Paul   32        70000.0
18    Quinn   45        80000.0
19     Rita   38        88000.0

### Task 6: Data Aggregation
Objective: Perform group-based aggregation.

Instructions:

Group the data by department and calculate the average salary for each department.

In [21]:
## Group by department and display with average salary of each department
grouped_department = df.groupby('department')['annual_salary'].mean().reset_index()
grouped_department

    department  annual_salary
0  Engineering        74750.0
1      Finance        91250.0
2           HR        62500.0
3    Marketing        77500.0
4        Sales        82000.0

Great work and well done on explaining your approach! Jose A